### ISSUE TITLE
How to make this lib support image ?

### ISSUE THREAD

**Issue by finscn** [skeeto/webgl-particles#4]
I'm a newbie of shader. (and with bad English, sorry)
Could you give me some advices ?
I want to use image as particles.
（ do something like this :　http://www.goodboydigital.com/pixijs/bunnymark_v3/　）
All particles use the same image file , but use different parts of the image. (like sprite-sheet)

Thanks.

**Comment by finscn** [comment]
I found some repos about `particles in shader`, but they are based on ThreeJS.
https://github.com/pwambach/threejs-particle-shader
https://github.com/squarefeet/ShaderParticleEngine
https://github.com/schteppe/gpu-physics.js

That's too complex to me (I don't anything about ThreeJS).
I see this repo is tiny & clear , and it's a great sample to learn that `How to present particles in shader`.

So I ask for your help .

Thank you very much.

**Comment by skeeto** [comment]
My article "A GPU Approach to Particle Physics" documents how this 
project works: http://nullprogram.com/blog/2014/06/29/ That's where 
you'd want to start in order to understand this code

**Comment by finscn** [comment]
Thanks. I've already read this article some days ago, and I could understand the most parts of it.
But I've still no idea about ` not use glPoint , use image  as the particles` .
 I know the reason is I'm too weak at WebGL and shader. So sad .

**Comment by finscn** [comment]
I know how to do that. Thanks
